wifi-cdmx {

  http {
    host = "0.0.0.0"
    host = ${?HTTP_HOST}
    port = 8080
    port = ${?HTTP_PORT}
  }

  database {
    url      = "jdbc:postgresql://localhost:5433/wificdmx"
    url      = ${?DB_URL}
    user     = "postgres"
    user     = ${?DB_USER}
    password = "postgres"
    password = ${?DB_PASSWORD}
    driver   = "org.postgresql.Driver"
    pool {
      max-connections    = 10
      min-idle           = 2
      connection-timeout = 30000
      idle-timeout       = 600000
    }
  }

  data {
    xlsx-url   = "https://datos.cdmx.gob.mx/dataset/0a2e3fb1-5ff0-4a64-9f3d-c065e7018858/resource/ae7f6877-53ee-4fbe-85a4-db8d773d637b/download/00-2025-wifi_gratuito_en_cdmx.xlsx"
    xlsx-url   = ${?DATA_URL}
    local-path = "data/wifi-cdmx.xlsx"
    local-path = ${?DATA_LOCAL_PATH}
  }
}

akka {
  loglevel = "INFO"
  http.server {
    idle-timeout    = 60s
    request-timeout = 30s
  }
}